
server:
  port: 8086
  servlet:
    context-path: /api


#spring配置
spring:
  profiles:
    active: @profileActive@


# Logger Config
logging:
  file:
    name: blog-admin-api.log
  pattern:
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'
#  me:
#    chenhz:
#      api: debug


# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: me.chenhz.api.entity

